#!/bin/bash
# Script to create all spec tree nodes
CLI="node --experimental-strip-types .claude/skills/sync-specs/scripts/specs-cli.ts"
ROOT=".harnesson/specs/draft"

# Level 2: Server Infrastructure
echo '{"_nodePath":"server-infrastructure","id":"server-infrastructure","name":"Server Infrastructure","level":2,"parent":"project","children":["health-check-api","port-auto-detection","agent-session-restore"],"isLeaf":false,"summary":"Core server infrastructure providing HTTP server setup, health monitoring, port management, and agent session restoration on startup.","goals":["Ensure reliable server startup with automatic port detection","Provide health check endpoint for connectivity verification","Restore agent sessions from database on server restart"],"design":"design/server-infrastructure.md","acceptanceCriteria":[{"given":"Server is starting","when":"Preferred port is occupied","then":"Automatically finds and uses the next available port"}],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","baseCommitMessage":"feat(specs): full sync","branch":"feature/specs-page","sourceFiles":["apps/server/src/index.ts","apps/server/src/routes/health.ts","apps/server/src/lib/find-port.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"server-infrastructure/health-check-api","id":"health-check-api","name":"Health Check API","level":3,"parent":"server-infrastructure","children":[],"isLeaf":true,"summary":"Returns server status and current timestamp via GET /api/health, used by frontend to verify backend connectivity.","goals":["Allow frontend to detect backend availability"],"specDetail":{"description":"Simple GET endpoint that returns JSON with status ok and current ISO timestamp.","parameters":["Returns {status:ok, timestamp:ISO8601}","Response time < 50ms"]},"constraints":["Must not require authentication","Must not depend on database"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","baseCommitMessage":"feat(specs): full sync","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/health.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"server-infrastructure/port-auto-detection","id":"port-auto-detection","name":"Port Auto-Detection","level":3,"parent":"server-infrastructure","children":[],"isLeaf":true,"summary":"Automatically finds an available TCP port if the preferred one is in use, trying up to 10 consecutive ports.","goals":["Ensure server can start without manual port configuration"],"specDetail":{"description":"Scans ports starting from preferred port, incrementing until an available one is found. Maximum 10 attempts.","parameters":["Default preferred port: 3456","Maximum attempts: 10","Scan range: preferred to preferred+10"]},"constraints":["Must not exceed 10 port attempts","Must release test socket before returning"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","baseCommitMessage":"feat(specs): full sync","branch":"feature/specs-page","sourceFiles":["apps/server/src/lib/find-port.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"server-infrastructure/agent-session-restore","id":"agent-session-restore","name":"Agent Session Restore","level":3,"parent":"server-infrastructure","children":[],"isLeaf":true,"summary":"Restores all persisted agent sessions from the database on server startup, reconnecting runtime state and adapters.","goals":["Allow agents to survive server restarts","Restore running/thinking sessions as idle to prevent stuck state"],"specDetail":{"description":"On startup, queries all non-destroyed sessions from DB, recreates ClaudeCodeAdapter instances, restores SDK session IDs, and resets running/thinking/waiting_for_input sessions to idle status.","parameters":["Restores all sessions with status not in [destroyed]","Resets running/thinking/waiting_for_input to idle"]},"constraints":["Must not block server startup if restore fails for individual sessions","Failed restores should set session status to error"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","baseCommitMessage":"feat(specs): full sync","branch":"feature/specs-page","sourceFiles":["apps/server/src/index.ts"]}}' | $CLI create-node --root $ROOT

# Level 2: Project Management
echo '{"_nodePath":"project-management","id":"project-management","name":"Project Management","level":2,"parent":"project","children":["project-crud","branch-management","folder-dialog","project-list-ui","project-actions","project-state"],"isLeaf":false,"summary":"Complete project lifecycle management including creation from local folders, cloning repos, fresh creation with git init, project listing, deletion, and Git branch operations.","goals":["Allow users to create and manage coding projects","Support multiple project sources: local folder, clone URL, fresh creation","Provide Git branch management within projects"],"design":"design/project-management.md","acceptanceCriteria":[{"given":"User wants to add a project","when":"They open a local folder via native dialog","then":"The project is created in the database and appears in the project list"}],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","baseCommitMessage":"feat(specs): full sync","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/projects.ts","apps/server/src/routes/branches.ts","apps/server/src/routes/open-folder.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-crud","id":"project-crud","name":"Project CRUD Operations","level":3,"parent":"project-management","children":["list-projects-api","get-project-api","create-project-api","delete-project-api"],"isLeaf":false,"summary":"REST API endpoints for project create, read, list, and delete operations with Prisma persistence.","goals":["Provide complete project CRUD via REST API"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","baseCommitMessage":"feat(specs): full sync","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/projects.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-crud/list-projects-api","id":"list-projects-api","name":"List Projects API","level":4,"parent":"project-crud","children":[],"isLeaf":true,"summary":"Returns all projects ordered by last updated via GET /api/projects.","specDetail":{"description":"Fetches all projects from the database, ordered by updatedAt descending.","parameters":["Endpoint: GET /api/projects","Returns: Project[] sorted by updatedAt desc"]},"constraints":["Returns empty array if no projects exist"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/projects.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-crud/get-project-api","id":"get-project-api","name":"Get Single Project API","level":4,"parent":"project-crud","children":[],"isLeaf":true,"summary":"Returns a single project by ID via GET /api/projects/:id.","specDetail":{"description":"Fetches a unique project by its ID.","parameters":["Endpoint: GET /api/projects/:id","Returns 404 if project not found"]},"constraints":["Must validate ID parameter"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/projects.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-crud/create-project-api","id":"create-project-api","name":"Create Project API","level":4,"parent":"project-crud","children":[],"isLeaf":true,"summary":"Creates a new project via POST /api/projects with deduplication by path and optional git init.","specDetail":{"description":"Creates project with name, path, description, source. Deduplicates by path. Supports git init for create source.","parameters":["Endpoint: POST /api/projects","Required fields: name, path","Optional: description, source, gitInit","Returns 201 on creation, existing project if path duplicate"]},"constraints":["name and path are required","Returns existing project if path already registered","git init failure does not block project creation"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/projects.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-crud/delete-project-api","id":"delete-project-api","name":"Delete Project API","level":4,"parent":"project-crud","children":[],"isLeaf":true,"summary":"Deletes a project by ID via DELETE /api/projects/:id.","specDetail":{"description":"Removes a project from the database.","parameters":["Endpoint: DELETE /api/projects/:id","Returns 404 if not found"]},"constraints":["Deletion is permanent"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/projects.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/branch-management","id":"branch-management","name":"Branch Management","level":3,"parent":"project-management","children":["list-branches-api","checkout-branch-api"],"isLeaf":false,"summary":"Git branch operations including listing local/remote branches and switching branches.","goals":["Allow users to view and switch Git branches"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/branches.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/branch-management/list-branches-api","id":"list-branches-api","name":"List Branches API","level":4,"parent":"branch-management","children":[],"isLeaf":true,"summary":"Lists local and remote git branches via GET /api/projects/:id/branches.","specDetail":{"description":"Spawns git commands to list local and remote branches, identifying the current branch.","parameters":["Endpoint: GET /api/projects/:id/branches","Returns: {local:[], remote:[], current:string|null, isGitRepo:boolean}"]},"constraints":["10 second timeout for git commands","Returns isGitRepo:false if not a git repo"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/branches.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/branch-management/checkout-branch-api","id":"checkout-branch-api","name":"Checkout Branch API","level":4,"parent":"branch-management","children":[],"isLeaf":true,"summary":"Switches to a specified git branch via POST /api/projects/:id/checkout.","specDetail":{"description":"Supports both local and remote branches. For remote branches, creates a local tracking branch.","parameters":["Endpoint: POST /api/projects/:id/checkout","Required: branch (string)","Returns: {success:boolean, branch?:string, error?:string}"]},"constraints":["Branch name must not contain newlines or null characters","10 second timeout for git commands"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/branches.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/folder-dialog","id":"folder-dialog","name":"Native Folder Dialog","level":3,"parent":"project-management","children":[],"isLeaf":true,"summary":"Opens a native OS folder selection dialog supporting macOS, Linux, and Windows.","specDetail":{"description":"POST /api/open-folder triggers platform-specific folder picker (osascript on macOS, zenity on Linux, Windows Forms on Windows).","parameters":["Endpoint: POST /api/open-folder","Returns: {path?:string, cancelled?:boolean, error?:string}"]},"constraints":["5 minute timeout for dialog","Returns cancelled:true if user cancels"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/server/src/routes/open-folder.ts","apps/server/src/lib/native-dialog.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-list-ui","id":"project-list-ui","name":"Project List UI","level":3,"parent":"project-management","children":[],"isLeaf":true,"summary":"Displays projects in card or list view with search filtering, empty state, and modals for cloning/creating projects.","specDetail":{"description":"Project list page that shows project cards or rows, with empty state prompting to add a project.","parameters":["Supports card and list view modes","Search filtering by name"]},"constraints":["Must show loading spinner while fetching projects"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/web/src/pages/ProjectsPage.tsx","apps/web/src/components/projects/ProjectList.tsx"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-actions","id":"project-actions","name":"Project Actions","level":3,"parent":"project-management","children":[],"isLeaf":true,"summary":"Frontend actions for opening folders, cloning repos, creating projects, and activating projects with loading state management.","specDetail":{"description":"React hook providing openFolder, cloneRepo, createProject, and openProjectWithPath actions with loading states.","parameters":["Loading states: isOpening, isCloning, isCreating","Server connectivity check before folder dialog"]},"constraints":["Must check server connectivity before opening folder dialog","Must show error alert if server is unreachable"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/web/src/hooks/useProjectActions.ts"]}}' | $CLI create-node --root $ROOT

echo '{"_nodePath":"project-management/project-state","id":"project-state","name":"Project State Management","level":3,"parent":"project-management","children":[],"isLeaf":true,"summary":"Zustand store managing project list, active project, branch state, view mode, and search query with localStorage persistence.","specDetail":{"description":"Central state store for project-related UI state including active project selection, branch info, and view preferences.","parameters":["View mode persisted in localStorage","Branch info includes local/remote lists and current branch"]},"constraints":["Must persist view mode across sessions"],"status":"draft","syncMeta":{"lastSyncAt":"2026-05-19T12:00:00Z","baseCommit":"def8141","branch":"feature/specs-page","sourceFiles":["apps/web/src/stores/projectStore.ts"]}}' | $CLI create-node --root $ROOT
